afficherannonce:
  path:     /afficherannonce
  defaults: { _controller: AnnonceBundle:Annonce:afficherAnnonce }
ajouterannonce:
  path:     /ajouterannonce
  defaults: { _controller: AnnonceBundle:Annonce:ajouterAnnonce }

detailannonce:
  path:     /detailannonce/{id}
  defaults: { _controller: AnnonceBundle:Annonce:detailAnnonce }
supprimerannonce:
  path:     /supprimerannonce/{id}
  defaults: { _controller: AnnonceBundle:Annonce:supprimer }
modifierannonce:
  path:     /modifierannonce/{id}
  defaults: { _controller: AnnonceBundle:Annonce:Modifier }

CatAdmin:
  path:     /CatAdmin
  defaults: { _controller: AnnonceBundle:Categorie:ajouterCat }

getCats:
  path:     /api/categorie
  defaults: { _controller: AnnonceBundle:Annonce:getCategories }

addCate:
  path:     /api/add/{iduser}/{idcat}/{nom}/{description}/{prix}/{images}/
  defaults: { _controller: AnnonceBundle:Annonce:addAnnonce }
  methods:  [POST]

update:
  path:     /api/update/{id}/{idcat}/{nom}/{description}/{prix}/{images}
  defaults: { _controller: AnnonceBundle:Annonce:updateAnnonce }

delete:
  path:     /api/delete/{id}
  defaults: { _controller: AnnonceBundle:Annonce:deleteAnnonce }

AnnonceByCats:
    path:     /api/annonce_cats/{id}
    defaults: { _controller: AnnonceBundle:Annonce:getAnnonceByCat }

DisplayAll:
  path:     /api/annonce/
  defaults: { _controller: AnnonceBundle:Annonce:displayAnnonce }

