messagerie_homepage:
    path:     /
    defaults: { _controller: MessagerieBundle:Default:index }
    methods:  GET
test:
    path:     /try/{id}
    defaults: { _controller: MessagerieBundle:Message:indext }
    methods:  GET

affich:
    path:     /affichMessages/{id}
    defaults: { _controller: MessagerieBundle:Message:affich }
Ajout:
    path:     /AjoutMessages/{id}
    defaults: { _controller: MessagerieBundle:Message:ajout }
    methods:  [GET, POST]


supp:
    path:     /suppMessages/{id}/{id1}
    defaults: { _controller: MessagerieBundle:Message:supp }
update:
    path:     /updateMessages/{id}/{id1}
    defaults: { _controller: MessagerieBundle:Message:update }
affichC:
    path:     /affichConversations
    defaults: { _controller: MessagerieBundle:Conversation:affichConversation }
AjoutC:
    path:     /ajoutConversation
    defaults: { _controller: MessagerieBundle:Conversation:AjoutConversation }
suppC:
    path:     /supprimerConversation/{id}
    defaults: { _controller: MessagerieBundle:Conversation:suppConversation }
updateC:
    path:     /updateConversation/{id}
    defaults: { _controller: MessagerieBundle:Conversation:updateConversation }
ajax_search:
    path:     /search
    defaults: { _controller: MessagerieBundle:Conversation:search }

affichCM:
    path:     /affichConversationsM/{id}
    defaults: { _controller: MessagerieBundle:Conversation:affichConversationM }
AjoutCM:
    path:     /ajoutConversationM
    defaults: { _controller: MessagerieBundle:Conversation:AjoutConversationM }
suppCM:
    path:     /supprimerConversationM/{id}
    defaults: { _controller: MessagerieBundle:Conversation:suppConversationM }
affichM:
    path:     /affichMessagesM/{id}
    defaults: { _controller: MessagerieBundle:Message:affichM }
AjoutM:
    path:     /AjoutMessagesM/{id}/{id1}/{id2}
    defaults: { _controller: MessagerieBundle:Message:ajoutM }
    methods:  [GET, POST]
updateM:
    path:     /updateMessages/{id}
    defaults: { _controller: MessagerieBundle:Message:updateM }
deleteM:
    path:     /supprimerMessages/{id}
    defaults: { _controller: MessagerieBundle:Message:suppMessageM }
